// <auto-generated />
namespace PassionProjectn01681774.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Weight : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Weight));
        
        string IMigrationMetadata.Id
        {
            get { return "202406292051368_Weight"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
